jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: My step
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
        run: |
          echo "ok"
